"""create videoas table

Revision ID: 0f56d02d723e
Revises: cd5f8322cb12
Create Date: 2025-09-18 07:29:38.648314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f56d02d723e'
down_revision: Union[str, None] = 'cd5f8322cb12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.create_table(
        'video',
        sa.Column('id', sa.String(), primary_key=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('preview_img', sa.String(), nullable=False),
        sa.Column('video', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False, server_default='Active'),
        sa.Column('created_at', sa.DateTime(timezone=False), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=False), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=False), nullable=True),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('file_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('videos', sa.Column('preview_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('archived_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_videos_status'), 'videos', ['status'], unique=False)
    op.create_index(op.f('idx_videos_deleted_at'), 'videos', ['deleted_at'], unique=False)
    op.create_index(op.f('idx_videos_created_at'), 'videos', ['created_at'], unique=False)
    op.alter_column('videos', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('videos', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('videos', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               nullable=False)
    op.alter_column('videos', 'status',
               existing_type=sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='videostatus'),
               type_=postgresql.ENUM('ACTIVE', 'ARCHIVED', name='video_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::video_status"))
    op.alter_column('videos', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('videos', 'published_at')
    op.drop_column('videos', 'age_rating')
    op.drop_column('videos', 'language')
    op.drop_column('videos', 'thumbnail_key')
    op.drop_column('videos', 'checksum')
    op.drop_column('videos', 'object_key')
    # ### end Alembic commands ###
