"""003_genre_unique

Revision ID: 2b66423060ab
Revises: 6090c0a87317
Create Date: 2025-09-22 13:13:39.018031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2b66423060ab'
down_revision: Union[str, None] = '6090c0a87317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('genre_name_key'), 'genre', type_='unique')
    op.create_unique_constraint('uq_genre_name_type', 'genre', ['name', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_genre_name_type', 'genre', type_='unique')
    op.create_unique_constraint(op.f('genre_name_key'), 'genre', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
