"""genre_id to videos

Revision ID: 5c73e80f0946
Revises: 66509b691894
Create Date: 2025-09-25 07:42:08.280116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5c73e80f0946'
down_revision: Union[str, None] = '66509b691894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('genre_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'video', 'genre', ['genre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.drop_column('video', 'genre_id')
    # ### end Alembic commands ###
