"""changing models

Revision ID: 66509b691894
Revises: e1bee68a71f3
Create Date: 2025-09-25 03:46:51.347073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '66509b691894'
down_revision: Union[str, None] = 'e1bee68a71f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('music_playlist_id_fkey'), 'music', type_='foreignkey')
    op.create_foreign_key(None, 'music', 'playlist', ['playlist_id'], ['id'])
    op.drop_constraint(op.f('statistics_ad_id_fkey'), 'statistics', type_='foreignkey')
    op.create_foreign_key(None, 'statistics', 'ad', ['ad_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statistics', type_='foreignkey')
    op.create_foreign_key(op.f('statistics_ad_id_fkey'), 'statistics', 'ad', ['ad_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'music', type_='foreignkey')
    op.create_foreign_key(op.f('music_playlist_id_fkey'), 'music', 'playlist', ['playlist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
