"""create videos

Revision ID: cd5f8322cb12
Revises: a1fb59aece84
Create Date: 2025-09-18 06:30:26.359312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cd5f8322cb12'
down_revision: Union[str, None] = 'a1fb59aece84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='video_status'), server_default='ACTIVE', nullable=False),
    sa.Column('file_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preview_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('duration_sec IS NULL OR duration_sec >= 0', name='ck_videos_duration_nonneg'),
    sa.CheckConstraint('size_bytes IS NULL OR size_bytes >= 0', name='ck_videos_size_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_videos_created_at', 'videos', ['created_at'], unique=False)
    op.create_index('idx_videos_deleted_at', 'videos', ['deleted_at'], unique=False)
    op.create_index('idx_videos_status', 'videos', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_videos_status', table_name='videos')
    op.drop_index('idx_videos_deleted_at', table_name='videos')
    op.drop_index('idx_videos_created_at', table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
