"""005_ads

Revision ID: 713287af33d6
Revises: 7ae705e7fe4c
Create Date: 2025-09-23 15:16:12.226684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '713287af33d6'
down_revision: Union[str, None] = '7ae705e7fe4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('video_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PROCESSING', 'FAILED', name='ad_status_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('statistics', sa.Column('ad_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('statistics_content_id_fkey'), 'statistics', type_='foreignkey')
    op.create_foreign_key(None, 'statistics', 'ad', ['ad_id'], ['id'], ondelete='CASCADE')
    op.drop_column('statistics', 'content_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('content_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'statistics', type_='foreignkey')
    op.create_foreign_key(op.f('statistics_content_id_fkey'), 'statistics', 'video', ['content_id'], ['id'], ondelete='CASCADE')
    op.drop_column('statistics', 'ad_id')
    op.drop_table('ad')
    # ### end Alembic commands ###
